### ISSUE TITLE
Overwatch job performance problem, Gold tier

### ISSUE THREAD

**Issue by moucode** [databrickslabs/overwatch#1061]
**Overwatch Version**
0.7.2.2

**Describe the bug**
I currently have the a problem with the Overwatch job. Overwatch is running into a timeout error daily (the timeout was manually set to 3 hours). The processing of the Bronze and Silver data in the job runs without problems. As soon as the processing of the Gold data starts in the job, there comes a point where no more activity is recorded in the job. The job indicates that it is still running, but the cluster's Ganglia data indicates that the cluster is no longer performing any actions until the timeout is reached. I have set the configurations as described in the documentation. Can you help here?

**Screenshots**

**Issue Reports**

**Comment by Neha-vs123** [comment]
Hi @moucode,

Could you please explain what configuration specifically are you talking about? Is it the csv config sheet or the job configuration?
Please try this method - Add the below command to the job cluster Spark Config section under Advanced Options:-
overwatch.tableLockTimeout 7200000

Run the job after adding this command line and let me know if the issue persists.

Regards,
Neha

**Comment by Neha-vs123** [comment]
Hi @moucode,

Can we have a call today or tomorrow at 10 am EST? For this issue, we need to try removing 2 scopes - dbsql and notebookCommands as a quick fix.
Just need to add these two scopes in the Excluded scopes column of the csv config sheet. If you are unsure on how to do it, we can do it by screensharing.
Please let me know if you need a call. My mail id - neha.vs@databricks.com

Regards,
Neha

**Comment by moucode** [comment]
Hi @Neha-vs123 , 

I adjusted the Spark Config and set there "overwatch.tableLockTimeout 7200000". Then I started the run and it did not fix the problem. 
I will now remove the 2 scopes - bsql and notebookCommands - and try it again. I will let you know then if I need the call. 

Thanks for your help.

**Comment by moucode** [comment]
Hi @Neha-vs123 ,

I have excluded the scopes you mentioned by entering the following in the csv file under excluded_scopes: audit:clusters:clusterEvents:pools:jobs:accounts:notebooks:sparkEvents

I executed 2 job runs, both were successful. However, the first run took almost 3 hours and the 2nd run took about 2h30m. Also, in both runs no new data was processed, although there should be some data delivered.

**Comment by Neha-vs123** [comment]
Hi @moucode,

Have you entered all these scopes (audit:clusters:clusterEvents:pools:jobs:accounts:notebooks:sparkEvents) in csv column?
The excluded scopes column is exclude the scopes. So you should enter only dbsql and notebookCommands in that column.
Or else all that major scopes will be excluded and that's why no new data was loaded.

**Comment by moucode** [comment]
Hi @Neha-vs123, 
But the documentation says that there should be scopes that should not be excluded from the pipelines.
![image](https://github.com/databrickslabs/overwatch/assets/70802558/31336c2f-f60b-4ad4-a39d-9934be4452ef)

Maybe I got it wrong, I will just add the two scopes dbsql and notebookCommands and test it again.

**Comment by Neha-vs123** [comment]
Hi @moucode 

Thanks for pointing it out. We will make the changes in document. 
That column should contain the scopes that should be excluded from the pipeline. If we leave it blank, none of the scopes will be excluded and it will load all available scopes. 

Regards,
Neha

**Comment by Neha-vs123** [comment]
Hi @moucode , It can also be interpreted in this way - those are the scopes that should not be excluded from the pipeline in normal case. If we want to exclude any scope, it should be entered in that column. We will make it more clear in document as it can be misinterpreted easily. 

Thanks,
Neha

**Comment by moucode** [comment]
Hi @Neha-vs123, 

I have done two runs now and it looks like it is working again. However, I would like to run more tests to be sure. 

But I have some questions regarding the problem:

- Why could the error be fixed after removing bsql and notebookCommands from our scope? What are the scopes and why does it not work for us?
- How can we avoid such errors in the future? Is there any way to identify and solve such problems faster? 
- We have not been able to run the Overwatch job successfully for a few days now. Now with the last successful run, is all the data for the missing days there? Is there any way to reload the data for the failed days correctly?

Thanks for your help!

**Comment by Neha-vs123** [comment]
Hi @moucode,

1. Scopes are the different segments of data overwatch is collecting from your environment. Each segment has it's own modules that generates the output data from bronze to gold. Please find more information in docs -https://databrickslabs.github.io/overwatch/dataengineer/modules/#scopes
There is no permanent issue with any of the scopes. In this case, there was a bug associated with these scopes in the latest overwatch JAR. So as a quick fix, we suggested to remove those scopes to avoid overwatch breakage. A new JAR will be released soon with all bug fixes applied. Once it is released, you can change the JAR and run overwatch using all the scopes.

2. We are getting new bugs since we are improving Overwatch performance and adding new features and functionalities on a timely basis. Overwatch is keep on changing, as a result we get some minor unknown bugs. But with each version we try our best to avoid such errors in future. 
If you find any such issues, the support team is here to help you fix it at the earliest. 

3. If you want to reload data, there is a process called rollback and rebuild. It will delete last n number of days data and then you can run overwatch job. It will reload data from the rolled back date.  But I would suggest to do it after the release of new JAR, as the current JAR won't collect dbsql and notebookCommands data.
Once it is released, we can have a meeting and do the entire rollback process by screensharing.

Regards,
Neha

**Comment by moucode** [comment]
Hi @Neha-vs123 ,

thank you very much for the detailed answer to my questions.

I have now run the Overwatch job for a few days. I have noticed that it only ever processes data from one workspace, even though I have specified two workspaces in the .csv file. The job starts to work with both workspaces, but at some point the following error appears in the bronze part: 

Read timed out
java.net.SocketTimeoutException: Read timed out
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

*** WARNING: skipped 35708 bytes of output ***


If I manually restart the job afterwards, the data of the missing workspace is processed again. Can you help me here as well?

**Comment by mohanbaabu1996** [comment]
`If I manually restart the job afterwards, the data of the missing workspace is processed again` — This is working fine, right? Data started collecting for the missing workspace?

**Comment by moucode** [comment]
@mohanbaabu1996 yes, this is working fine. But correct would be when both workspaces are processed in only one Overwatch job.

**Comment by mohanbaabu1996** [comment]
Let me know which timezone you are in, and we can have a quick call.
We're from IST timezone.

**Comment by moucode** [comment]
my timezone is UTC+2

**Comment by moucode** [comment]
Hi @Neha-vs123 @mohanbaabu1996, I still have this problem and am waiting for your response. Can you help me?

**Comment by mohanbaabu1996** [comment]
Hi @moucode ,

Apologies, Can you please share your email ID to send the invite?
Are you based in the Eastern European time zone? If yes, will 11:30 a.m. EET work?

**Comment by moucode** [comment]
@mohanbaabu1996 Can you give me your e-mail address? I will then contact you and we can arrange a meeting. Thank you!

**Comment by mohanbaabu1996** [comment]
mohan.baabu@databricks.com
neha.vs@databricks.com

**Comment by mohanbaabu1996** [comment]
Thanks for joining the call, If you have any other issues, please email us
