### ISSUE TITLE
Limiting API Call Rate

### ISSUE THREAD

**Issue by FastLee** [databrickslabs/overwatch#138]
Running OW in a production environment, we're observing:
> 429 Client Error: Too Many Requests for url

A configurable rate limiter will allow us to prevent Overwatch from impacting the workspace health.

The reported error is on Azure DB

**Comment by GeekSheikh** [comment]
Right, as mentioned internally, this is staged for 0.4.2 release.

**Comment by GeekSheikh** [comment]
Full rate limiting will be enabled in 0.4.2 but a hotfix will be cut for 0.4.13 that will implement a fix that was merged into databricks 3.42 platform (on/around March 23rd).

Scenario -- Interactive cluster executes notebook -- required API call prior to Databricks platform 3.42.

TLDR
[Hard coded high threadcount](https://github.com/databrickslabs/overwatch/blob/993ea86e956e7e01453fc58de33e2543392ea957/src/main/scala/com/databricks/labs/overwatch/pipeline/SilverTransforms.scala#L892) for workaround prior to Databricks 3.42. Threads were left at 24, only in edge cases is this method utilized to pull job run metadata due to missing data corrected via internal ES-74247. This will be lowered to 4 and only be applied for dates < April 01, 2021 where this scenario ocurrs.
