### ISSUE TITLE
Cost metrics were reflected only from Jan 4th 2022

### ISSUE THREAD

**Issue by saikumar-gouddubbaka** [databrickslabs/overwatch#312]
Team,

Recently we have migrated to 0.6.0.3 but the cost tables "jobruncostpotentialfact_gold" & "clusterstatefact_gold" has the data only from Jan 04th 2022. where as for all other tables the data is reflected from primordialDateString

Can you please help.

**Comment by Anusha-Sure** [comment]
Hi Saikumar,

Please confirm from where you have migrated to 0.6.0.3 and also share pipeline_report of your ETL database.

Regards,
Anusha

**Comment by saikumar-gouddubbaka** [comment]
Hi Anusha,

We have migrated from 0.5.0.6 to 0.6.0.3 with the help of mohan & Neha from your team. I will forward the pipe report to your mail.

**Comment by GeekSheikh** [comment]
Don't worry, we'll get you straightened out. This likely means that there was an issue in one more of the modules during the upgrade. If you have already finalized the upgrade, we'll just need to review the pipReport to see what went wrong, correct it and then the subsequent run will reload that data for you. I'm sure @Anusha-Sure @mohanbaabu1996 or @Neha-vs123 will be able to get you fixed up on this.

**Comment by Anusha-Sure** [comment]
Hi Sai,

Thank you for sharing the pipreport; we've been working on this issue externally for the past few days. Because the job_id field in sparkJob was null in 0.6.0.3, the same issue occurred. Please upgrade to version 0.6.0.4 and see the attached solution for the similar situation [here](https://github.com/databrickslabs/overwatch/issues/310).

Please let us know when you are available the following week.

Regards,
Anusha

**Comment by Anusha-Sure** [comment]
Hi Sai,

I'd like to know if the above issue has been resolved. Please let us know we can set up a call if it exists.

Regards,
Anusha
