### ISSUE TITLE
Integrate overwatch with AWS SecretsManager

### ISSUE THREAD

**Issue by dyon78** [databrickslabs/overwatch#318]
Add possibility to use secrets from AWS Secrets Manager instead of databricks keys

**Comment by mohanbaabu1996** [comment]
Hi @dyon78 , Currently overwatch doesn't support integrating with AWS secret manager. 
Instead, use the databricks CLI to create a secret.

**Comment by dyon78** [comment]
Hi @mohanbaabu1996, 
Let's exactly why I've created this ticket - because it's yet not supported. We had a meeting with wide audience month ago where this question was raised and we were given an advise to create a ticket to have this enhancement. 
We can escalate this further if you're not sure about taking this into work.

Regards,
Dmytro

**Comment by GeekSheikh** [comment]
@alexott -- are you familiar with this or have any idea how much work is involved in integrating this?

**Comment by alexott** [comment]
I need to look, but it could be quite significant enhancement as we'll need to bring completely new APIs. Ideally, we just need to have secret scopes baked by AWS Secret Manager, like we have for Azure  KeyVault

**Comment by dyon78** [comment]
Hi @alexott , 
   Could you estimate possibility of implementing the feature and efforts?

Regards,
Dmytro

**Comment by GeekSheikh** [comment]
@dyon78 -- at present there are no plans to directly implement this feature into Overwatch. This is due to security risks that we feel would never get through legal / security review. This is really a Databricks feature request. Support for AWS Secrets manager should be integrated with Databricks secrets support not custom built into Overwatch. Please work with your account team to ensure that this feature request has been captured and getting the attention it deserves.
