### ISSUE TITLE
Databricks Overwatch jobruncostpotentialfact table has null job_run_cluster_util value for most clusters

### ISSUE THREAD

**Issue by johna-am** [databrickslabs/overwatch#450]
Databricks Overwatch is populating the jobruncostpotentialfact table and this is has null values for column job_run_cluster_util value for most clusters. As a result, I can't analyze the utilization of most of our clusters using the queries provided by Databricks.

**Comment by GeekSheikh** [comment]
Hello @johna-am -- I will get a support analyst assigned to this in <24h. That said, please note that the job_run_cluster_util field DOES require logging is enabled on the clusters or this field will be null. If your clusters are set to log then the support analyst will take it from here. We'll get you fixed up, thanks for reaching out.

**Comment by mohanbaabu1996** [comment]
Hi @johna-am ,

Have you tried enabling logging path to all the clusters ? If you need more clarification we can connect in a call and explain you.
Kindly consider i'm from India (IST time zone). Please have a look into [docs ](https://databrickslabs.github.io/overwatch/faq/#q4-how-to-config-the-cluster-logs-path)for enabling logs.

**Comment by mohanbaabu1996** [comment]
Hi @johna-am , 

Have you used this method?

**Comment by johna-am** [comment]
I met with Shubham Pachori and Bryan Li from Databricks last Tuesday to discuss and troubleshoot this problem. We discovered that clusters that were saving logs to a folder that Overwatch scans were also missing this data. Shubham said he would reach out to the development team. We also did some queries against the jobruncostpotentialfact table, and saw that for the offending rows, spark_task_runtimMS, and spark_task_runtime_H were null, and these columns are used to calculate job_run_cluster_util.

**Comment by mohanbaabu1996** [comment]
Thanks @johna-am for the updates. 

1. Does the overwatch have access to cluster logging storage account/container(if it's azure) or S3 bucket(AWS) ?
2. Spark_task_runtimMS and Spark_task_runtime_H are null, overwatch will capture these spark information from each cluster and it try to save it to a particular storage. Here it's empty/null because cluster doesn't have [enabled ](https://databrickslabs.github.io/overwatch/faq/#q4-how-to-config-the-cluster-logs-path)path. So job_run_cluster_util value is getting null

If the path is mounted and not enabled to any cluster, then make the process automated by following the [steps ](https://databrickslabs.github.io/overwatch/faq/#q7-id-like-to-have-cluster-policies-to-ensure-all-future-interactive-and-automated-clusters-have-an-appropriate-logging-location)from the docs

**Comment by mohanbaabu1996** [comment]
Hi, if this works please let me know. 
Thanks!

**Comment by mohanbaabu1996** [comment]
Hi @johna-am ,

Please feel free to re-open this ticket, if you still have the issue.
Thanks!
