### ISSUE TITLE
Run fails when workspace job count is above 2.0 job API limit

### ISSUE THREAD

**Issue by manojmallela** [databrickslabs/overwatch#458]
The current release of overwatch ([v0.6.1.1](https://github.com/databrickslabs/overwatch/releases/tag/v0.6.1.1)) uses the `/api/2.0/jobs/list` endpoint for getting job info. For workspace with job count >3000 the API call fails `QUOTA_EXCEEDED`  error as shown below. The error message suggests to use to the newer `/api/2.1/jobs/list` endpoint.

**Error:**
```
ApiCallFailure: {"error_code":"QUOTA_EXCEEDED","message":"The number of jobs to return has exceeded allowed threshold of 3000. The current number of visible jobs is 3014. If this limit is hit, some percentage of /api/2.0/jobs/list will fail. We recommend switching to 2.1 API: https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsList For more questions, please contact support."}
at com.databricks.labs.overwatch.ApiCall.executeGet(ApiCall.scala:248)
	at com.databricks.labs.overwatch.env.Workspace.getJobsDF(Workspace.scala:58)
	at com.databricks.labs.overwatch.pipeline.Bronze.appendJobsProcess$lzycompute(Bronze.scala:96)
	at com.databricks.labs.overwatch.pipeline.Bronze.appendJobsProcess(Bronze.scala:95)
	at com.databricks.labs.overwatch.pipeline.Bronze.$anonfun$executeModules$1(Bronze.scala:206)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at com.databricks.labs.overwatch.pipeline.Bronze.executeModules(Bronze.scala:202)
	at com.databricks.labs.overwatch.pipeline.Bronze.run(Bronze.scala:229)
	at com.databricks.labs.overwatch.BatchRunner$.main(BatchRunner.scala:46)
```

**Code:**
https://github.com/databrickslabs/overwatch/blob/ac52b259e95d38325ddcc5c10c5a27f16f26ec2d/src/main/scala/com/databricks/labs/overwatch/ApiCall.scala#L83

cc: @GeekSheikh

**Comment by GeekSheikh** [comment]
Hi @manojmallela This means that you cannot execute any more jobs inside the Databricks workspace since the workspace is already processing 3000 (limit) job runs at the time this job tried to launch. You can try it again at an off hour. Also, please note that I saw some internal thread that we just increased this hard limit to 10K, please work with your account team to see if you can get this increased. 

Please feel free to reopen if you need any followups

**Comment by GeekSheikh** [comment]
@Sriram-databricks 

This is due to a jobs/list limitation of 3000 results. It appears that jobs/list api v 2.0 does not have pagination support but v2.1 does. 

Let's see if there are any schema conflicts when merging jobs/list v2.1 with existing jobs_snapshot table schema. We'll also need to verify downstream dependencies on the new schema to ensure compatibility in silver / gold dependencies before we switch. 

We had intended on migrating to v2.1 in Overwatch version 6.2.0 but due to this error at customer site, let's see what it will take to pull this forward into 0.6.1.2 release.

Please review adding in v2.1 for jobs/list into APICallV2 and APIMeta appropriately and see what blows up.

Thanks.

**Comment by GeekSheikh** [comment]
@Sriram-databricks -- please add a setter for APICallV2 and APIMeta appropriately so that the user can pass in the API version. Currently it's hard-coded to 2.0. User should be able to choose a version of the API endpoint.

Ex: jobs 2.1 instead of 2.0

Currently the jobs API is the only one with another version but this will future proof us and is likely necessary to resolve this anyway, I just want to enable this functionality in a more formal / appropriate way as part of this

**Comment by GeekSheikh** [comment]
pre-requisite = #477

**Comment by Sriram-databricks** [comment]
enhancement has been completed.
https://github.com/databrickslabs/overwatch/pull/484
