### ISSUE TITLE
Description column in sparkexecution table is truncated

### ISSUE THREAD

**Issue by alinealvarez0107** [databrickslabs/overwatch#534]
Hi, good morning! 

I'm facing a problem with description column in sparkexecution table because it is truncated and I need to see the entire value.

Is there any way to get this information?

![SparkTableOverwatch](https://user-images.githubusercontent.com/110247311/193050370-f1b7de20-acf2-4215-8516-0826d5313d9c.PNG)

**Comment by Neha-vs123** [comment]
Hi @alinealvarez0107 ,

We are looking into it. I will get back to you once I get the solution.

Regards,
Neha

**Comment by Neha-vs123** [comment]
Hi @alinealvarez0107,

We suggest you enable Verbose audit logs from the workspace. Go to Admin Console - Workspace Settings - Advanced - Verbose Audit Logs.
This helps in getting the command-level execution details.

The description column in the sparkExecution table cannot be expanded since it is intentionally truncated due to its potential size and risk to the VM.

Regards,
Neha

**Comment by Neha-vs123** [comment]
Hi @alinealvarez0107,

Overwatch upgrade 070 has been released. We suggest you upgrade to the latest version by referring to the [document](https://databrickslabs.github.io/overwatch/changelog/). It will fix a lot of data quality issues.
Let me know if you need any help in doing the same.

Regards,
Neha

**Comment by Neha-vs123** [comment]
Hi @alinealvarez0107,

I am closing the ticket for now. Feel free to open it if you have any doubts/issues with Overwatch. 

Regards,
Neha

**Comment by alinealvarez0107** [comment]
Hi @Neha-vs123 thank you so much!
I'll try to update the version and any problems I'll get back to you.
Regards, 
Aline
