### ISSUE TITLE
Inconsistent DBU and cost totals

### ISSUE THREAD

**Issue by tanonev** [databrickslabs/overwatch#597]
Hi,

I have been working with your consultants to get Overwatch set up in my workspace, and as a sanity check I tried comparing the costs and DBU totals for my workspace against those reported in the Databricks account UI.  Both numbers are significantly off, even after accounting for potential effects of time zone differences.
Here is the view from the Databricks UI:
<img width="1904" alt="Screen Shot 2022-11-03 at 1 05 37 AM" src="https://user-images.githubusercontent.com/1619236/199672250-60f6666e-713e-4b3d-851b-bfc5f4173a5a.png">
Here is the view from the notebook (Workspaces_V2) provided by the Databricks consultant:
<img width="1904" alt="Screen Shot 2022-11-03 at 1 06 34 AM" src="https://user-images.githubusercontent.com/1619236/199672510-395e4285-a423-40bf-844d-da2642783c8a.png">
Note that Overwatch significantly (but inconsistently) overestimates the cost.  And this is despite having configured it with our contract prices of $0.xx/DBU for interactive and $0.xx/DBU for job-only, which are *lower* than the (incorrect) assumptions made in the Databricks UI of $0.xx/DBU for interactive and $0.xx/DBU for job-only.

The consultants asked me to file this issue here for visibility.

**Comment by GeekSheikh** [comment]
Hello,

After a review, we have identified an issue in the Overwatch core in the way that DBSQL prices are calculated. Thank you for bringing this to our attention. Please see #601 for more details on this and we will be publishing a patch very soon to address this.

In the meantime I have added a little adjustment to your dashboard query to calculate a close estimate to the actuals. As you can see in the image below, we are much closer to accurate now (nearly exact). The adjustment adds a discount based on the difference between your interactive and dbsql costs and then divides by 2 when dbsql uses photon since interactive photon doubles dbu count. 

```python
photon_kicker = when(col("runtime_engine") == "PHOTON", lit(2)).otherwise(lit(1))
is_dbsql = when(get_json_object(col("custom_tags"), "$.SqlEndpointId").isNotNull(), lit(True)).otherwise(lit(False))
cluster_master = masters.cluster_master_filter(includeWeekend = include_weekends,onlyWeekend = only_weekends)\
  .withColumn("total_dbu_cost", when(is_dbsql, ((col("total_dbu_cost") * 0.xxxx) / photon_kicker)).otherwise(col("total_dbu_cost")))
```

so for the immediate term you have a way to accurately calculate price and shortly we'll have the 07003 patch out which will give you the accurate counts by default.

<img width="1534" alt="image" src="https://user-images.githubusercontent.com/10840635/200011194-7d75f8bf-26fc-43ca-b1dd-0da242dbd1f9.png">
