### ISSUE TITLE
Near duplicate rows in cluster gold table

### ISSUE THREAD

**Issue by frosforever** [databrickslabs/overwatch#806]
**Overwatch Version**
`0.7.0.1`

What does it mean when the `cluster` gold table has near duplicate rows? Some clusters show up twice with everything exactly the same except for `unixTimeMS` (off by 2ms), and `__overwatch_ctrl_noise`. It is not violating the key constraint as the `unixTimeMS` is indeed different but what would lead to such a thing? 

Thanks!

**Comment by mohanbaabu1996** [comment]
Hi @frosforever,

- Duplicate rows are getting only in cluster table ? Could you please confirm that duplicates are in **cluster_gold** table from ETL database
- How long have you been running overwatch ?
- In your old ticket #744 , you've mentioned the overwatch version as 0710 and here it mentioned as 0701. Could you please confirm

Thanks,
Mohan Baabu

**Comment by mohanbaabu1996** [comment]
Hi @frosforever ,

Thanks for the confirmation!
In cluster table, we collect the cluster snapshot details when the cluster gets create/edit/delete. Do you have any sample on what near duplicates you're mentioning. If you're already upgraded your overwatch to 0712, then please run the rollback script attached, so that it will re-generate the old 30 days data to the new logic. 
[0711_DataRepair_Script_Rollback.dbc.zip]
Please make sure the change this variable to false, **val isDryRun = true**
(https://github.com/databrickslabs/overwatch/files/10938784/0711_DataRepair_Script_Rollback.dbc.zip)

**Comment by frosforever** [comment]
I ran the rollback script and then ran overwatch using `0.7.1.2` and still have duplicates. Was I supposed to use an older overwatch version? 

![image](https://user-images.githubusercontent.com/1630422/224419629-4e2c617f-c592-4ff6-a1bd-6560674de58e.png)

An example with some identifying info removed:
![image](https://user-images.githubusercontent.com/1630422/224419898-30d71a6c-4db0-4ce6-865d-0e22acd84bfb.png)

**Comment by mohanbaabu1996** [comment]
Even the column action also the same ?

**Comment by frosforever** [comment]
That is correct. See the example screenshot I provided or in table form below:

|          cluster_id|action|   unixTimeMS|          timestamp|      date|        cluster_name|driver_node_type| node_type|num_workers|autoscale|auto_termination_minutes|enable_elastic_disk|is_automated|cluster_type|    security_profile|    cluster_log_conf|        init_scripts|         custom_tags|cluster_source|      aws_attributes|azure_attributes|      spark_env_vars|          spark_conf|     acl_path_prefix|driver_instance_pool_id|instance_pool_id|driver_instance_pool_name|instance_pool_name|   spark_version|runtime_engine|   idempotency_token|deleted_by| created_by|last_edited_by|__overwatch_ctrl_noise|    Pipeline_SnapTS|     Overwatch_RunID|
|--------------------|------|-------------|-------------------|----------|--------------------|----------------|----------|-----------|---------|------------------------|-------------------|------------|------------|--------------------|--------------------|--------------------|--------------------|--------------|--------------------|----------------|--------------------|--------------------|--------------------|-----------------------|----------------|-------------------------|------------------|----------------|--------------|--------------------|----------|-----------|--------------|----------------------|-------------------|--------------------|
|0308-025047-hfdipoew|create|1678243847624|2023-03-07 21:50:47|2023-03-08|job-1024043671143...|      i3.4xlarge|i3.2xlarge|         10|     null|                       0|              false|        true|    Standard|{false, false, fa...|{"s3":{"destinati...|[{"s3":{"destinat...|{"Department":"Da...|          null|{availability -> ...|            null|{"PYSPARK_PYTHON"...|{"spark.databrick...|/clusters/jobs/10...|                   null|            null|                     null|              null|11.3.x-scala2.12|      STANDARD|jobs/job-10240436...|      null|JobsService|          null|                     0|2023-03-08 13:37:06|3164372d58b544009...|
|0308-025047-hfdipoew|create|1678243847626|2023-03-07 21:50:47|2023-03-08|job-1024043671143...|      i3.4xlarge|i3.2xlarge|         10|     null|                       0|              false|        true|    Standard|{false, false, fa...|{"s3":{"destinati...|[{"s3":{"destinat...|{"Department":"Da...|          null|{availability -> ...|            null|{"PYSPARK_PYTHON"...|{"spark.databrick...|/clusters/jobs/10...|                   null|            null|                     null|              null|11.3.x-scala2.12|      STANDARD|jobs/job-10240436...|      null|JobsService|          null|                    11|2023-03-08 13:37:06|3164372d58b544009...|

**Comment by mohanbaabu1996** [comment]
Hi @frosforever ,

Could you confirm that all the clusters are triggered by job cluster ? Because when the job try to create cluster by sending multiple request, in that one request will create the cluster. In the above example, if you look at **action** & **unixTimeMS** column,  both has create action but differs with 2 ms and that one is used for jobrun

**Comment by frosforever** [comment]
All clusters are, and have always been, triggered the same way using job API runs/submit (https://docs.databricks.com/dev-tools/api/2.0/jobs.html#runs-submit) with `new_cluster` defined. 

I'm not sure I follow. Why am I only seeing duplicates now?

**Comment by GeekSheikh** [comment]
@frosforever -- this is a function of the scalable Databricks workflow scheduler. When a job launches it sends "at least one" request to create the cluster. These at least once semantics means that there are in fact two events sent but only one is accepted -- it results in an intentional race condition in the product. As you can see there is a difference of 2 milliseconds between these requests so these are in fact two different requests from the jobs-sheduler.

Say you want to find the name of a cluster when a job run launches. The run launches at time 10 and it spawns two cluster create events at 12 and 14. I would lookup the value for the first event after 10 (i.e. record from time 12). We have a function `lookupWhen` that will likely help you in these time-series joins. The [docs are here](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#joining-with-slow-changing-dimensions-scd) for this.

**Comment by frosforever** [comment]
Interesting that was functioning as designed. My `cluster` table has data back to 2023-01-24 but duplicates only started showing up recently on 2023-03-08. I guess that's just luck then.

**Comment by GeekSheikh** [comment]
If I recall correctly - your first run was on / around that time. Please note that a first / historical run works differently than subsequent runs as records often have to be initialized and imputed on the first run to get complete records. I'm guessing this is why you only began seeing them around this time.

**Comment by frosforever** [comment]
Reasonable enough. thanks for the insight.
