### ISSUE TITLE
How to set minEventsPerTrigger in Overwatch 0.7.1.3

### ISSUE THREAD

**Issue by mikhilpaul** [databrickslabs/overwatch#905]
As per v0.7.1.3 docs, configuration excel file does not have a field to mention minEventsPerTrigger. This is one of the optimization techniques mentioned in the [docs](https://databrickslabs.github.io/overwatch/dataengineer/advancedtopics/#additional-optimization-considerations).

Could you let me know how can i specify this audit log config for v0.7.1+?

**Comment by mikhilpaul** [comment]
thank you for you response! at the moment for 3 workspaces the overwatch process takes about 40 mins, which from the docs i understand is normal. But at the same time, in the optimization docs it was mentioned that for less than 32 partition (which is in my case) and since i have 200 events on average, min and max trigger must be increased immediately which is why i was attempting to do but couldnt find an option to do so in the latest version of config. 

Thus, just wanted to check if its possible to provide the same argument in the new version of the config.

**Comment by GeekSheikh** [comment]
how many partitions do you have? this doesn't change the number of events that will be ingested, just the number of events per stream mini-batch. Changing the partitions to 32 will increase perf in the bronze land stage where we pull the audit logs into OW but changing these values I don't think will really help you. No there's no way to adjust these in the latest release. I will file a ticket to get these re-exposed in later versions.

Look at the time to complete module 1004 (audit log bronze) if you have <32 partitions in your EH, the solution to make this go faster is to increase the partition count. these flags won't change your perf.

`minEventsPerTrigger` (default 10) should be increased if your stream is never stopping because you are getting events faster than the stream can go -- not the case here

`maxEventsPerTrigger` (default 10000) can be increased but doing so can result in memory issues and lower perf based on cluster configs -- recommend don't change this.

**Comment by mikhilpaul** [comment]
Yes all the tables you mentioned are the ones that take the most time. So i think this is normal. Looking forward to the improvements. thanks again for this great tool!
